name: Wordlist Index Updater

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  publish:
    name: Publish index
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
      - name: Install dependencies
        run: |
          dotnet tool install -g SAPTeam.Kryptor.Tool --prerelease
        shell: bash
      - name: Update Index
        run: |
          kryptor wordlist index -v wordlists.json
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: SAPTeamDEV <sapteam.mail@gmail.com>
          commit_message: Update wordlist index
      